### ISSUE TITLE
Examples no longer work for new macOS

### ISSUE THREAD

**Issue by kwccoin** [ShonFrazier/lib6502#2]
Even I copy the lib6502.h to examples and use instead of gcc-11 (not clang), the ld cannot run to get the examples to work.  Guess it is so many years, ...

**Comment by ShonFrazier** [comment]
Works for me. macOS Big Sur 11.5.2, gcc-mp-11 (MacPorts gcc11 11.2.0_1) 11.2.0

From the root of the repo, try:
```
cd examples
gcc-11 -L .. -I .. -l 6502 -o lib1 lib1.c
```
This tells gcc to find libraries in `..`, find headers ("includes") in `..`, link with 6502 (it'll prepend `lib` and try suffixes `.a`, `.so`, maybe `.dylib`)
